const transcription = [
  {
    channelTag: 0,
    alternatives: [
      {
        words: [
          {
            word: 'Hey',
            endTime: { nanos: 700000000, seconds: '0' },
            startTime: { nanos: 200000000, seconds: '0' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'there.',
            endTime: { nanos: 900000000, seconds: '0' },
            startTime: { nanos: 700000000, seconds: '0' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'Thanks',
            endTime: { nanos: 100000000, seconds: '1' },
            startTime: { nanos: 900000000, seconds: '0' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'for',
            endTime: { nanos: 400000000, seconds: '1' },
            startTime: { nanos: 100000000, seconds: '1' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'checking',
            endTime: { nanos: 600000000, seconds: '1' },
            startTime: { nanos: 400000000, seconds: '1' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'out',
            endTime: { nanos: 700000000, seconds: '1' },
            startTime: { nanos: 600000000, seconds: '1' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'this',
            endTime: { nanos: 900000000, seconds: '1' },
            startTime: { nanos: 700000000, seconds: '1' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'open',
            endTime: { nanos: 200000000, seconds: '2' },
            startTime: { nanos: 900000000, seconds: '1' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'source',
            endTime: { nanos: 500000000, seconds: '2' },
            startTime: { nanos: 200000000, seconds: '2' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'tool.',
            endTime: { nanos: 900000000, seconds: '2' },
            startTime: { nanos: 500000000, seconds: '2' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'What',
            endTime: { nanos: 300000000, seconds: '3' },
            startTime: { nanos: 900000000, seconds: '2' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'this',
            endTime: { nanos: 600000000, seconds: '3' },
            startTime: { nanos: 300000000, seconds: '3' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'tool',
            endTime: { nanos: 0, seconds: '4' },
            startTime: { nanos: 600000000, seconds: '3' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'is,',
            endTime: { nanos: 300000000, seconds: '4' },
            startTime: { nanos: 0, seconds: '4' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'is',
            endTime: { nanos: 400000000, seconds: '4' },
            startTime: { nanos: 300000000, seconds: '4' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'kind',
            endTime: { nanos: 300000000, seconds: '5' },
            startTime: { nanos: 400000000, seconds: '4' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'of',
            endTime: { nanos: 400000000, seconds: '5' },
            startTime: { nanos: 300000000, seconds: '5' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'like',
            endTime: { nanos: 600000000, seconds: '5' },
            startTime: { nanos: 400000000, seconds: '5' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'a',
            endTime: { nanos: 0, seconds: '6' },
            startTime: { nanos: 600000000, seconds: '5' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'd',
            endTime: { nanos: 300000000, seconds: '6' },
            startTime: { nanos: 0, seconds: '6' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'script',
            endTime: { nanos: 900000000, seconds: '6' },
            startTime: { nanos: 300000000, seconds: '6' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'editor,',
            endTime: { nanos: 100000000, seconds: '7' },
            startTime: { nanos: 900000000, seconds: '6' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'where',
            endTime: { nanos: 200000000, seconds: '8' },
            startTime: { nanos: 100000000, seconds: '7' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 500000000, seconds: '8' },
            startTime: { nanos: 200000000, seconds: '8' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'text',
            endTime: { nanos: 0, seconds: '9' },
            startTime: { nanos: 500000000, seconds: '8' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'is',
            endTime: { nanos: 700000000, seconds: '9' },
            startTime: { nanos: 0, seconds: '9' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 400000000, seconds: '10' },
            startTime: { nanos: 700000000, seconds: '9' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'primary',
            endTime: { nanos: 900000000, seconds: '10' },
            startTime: { nanos: 400000000, seconds: '10' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'source',
            endTime: { nanos: 200000000, seconds: '11' },
            startTime: { nanos: 900000000, seconds: '10' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'of',
            endTime: { nanos: 400000000, seconds: '12' },
            startTime: { nanos: 200000000, seconds: '11' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 600000000, seconds: '12' },
            startTime: { nanos: 400000000, seconds: '12' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'cuts',
            endTime: { nanos: 0, seconds: '13' },
            startTime: { nanos: 600000000, seconds: '12' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'in',
            endTime: { nanos: 200000000, seconds: '13' },
            startTime: { nanos: 0, seconds: '13' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 300000000, seconds: '13' },
            startTime: { nanos: 200000000, seconds: '13' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'edits',
            endTime: { nanos: 700000000, seconds: '13' },
            startTime: { nanos: 300000000, seconds: '13' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'for',
            endTime: { nanos: 200000000, seconds: '14' },
            startTime: { nanos: 700000000, seconds: '13' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 400000000, seconds: '14' },
            startTime: { nanos: 200000000, seconds: '14' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'video.',
            endTime: { nanos: 700000000, seconds: '14' },
            startTime: { nanos: 400000000, seconds: '14' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'So',
            endTime: { nanos: 200000000, seconds: '15' },
            startTime: { nanos: 700000000, seconds: '14' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 400000000, seconds: '15' },
            startTime: { nanos: 200000000, seconds: '15' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'idea',
            endTime: { nanos: 600000000, seconds: '15' },
            startTime: { nanos: 400000000, seconds: '15' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'is',
            endTime: { nanos: 900000000, seconds: '15' },
            startTime: { nanos: 600000000, seconds: '15' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'to',
            endTime: { nanos: 0, seconds: '16' },
            startTime: { nanos: 900000000, seconds: '15' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'give',
            endTime: { nanos: 200000000, seconds: '16' },
            startTime: { nanos: 0, seconds: '16' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'an',
            endTime: { nanos: 300000000, seconds: '16' },
            startTime: { nanos: 200000000, seconds: '16' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'edited',
            endTime: { nanos: 700000000, seconds: '16' },
            startTime: { nanos: 300000000, seconds: '16' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'video',
            endTime: { nanos: 800000000, seconds: '16' },
            startTime: { nanos: 700000000, seconds: '16' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'like',
            endTime: { nanos: 0, seconds: '17' },
            startTime: { nanos: 800000000, seconds: '16' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'a',
            endTime: { nanos: 100000000, seconds: '17' },
            startTime: { nanos: 0, seconds: '17' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'Word',
            endTime: { nanos: 400000000, seconds: '17' },
            startTime: { nanos: 100000000, seconds: '17' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'document',
            endTime: { nanos: 700000000, seconds: '17' },
            startTime: { nanos: 400000000, seconds: '17' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'in',
            endTime: { nanos: 800000000, seconds: '18' },
            startTime: { nanos: 700000000, seconds: '17' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'this',
            endTime: { nanos: 900000000, seconds: '18' },
            startTime: { nanos: 800000000, seconds: '18' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'is',
            endTime: { nanos: 100000000, seconds: '19' },
            startTime: { nanos: 900000000, seconds: '18' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'an',
            endTime: { nanos: 200000000, seconds: '19' },
            startTime: { nanos: 100000000, seconds: '19' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'open',
            endTime: { nanos: 300000000, seconds: '19' },
            startTime: { nanos: 200000000, seconds: '19' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'source',
            endTime: { nanos: 500000000, seconds: '19' },
            startTime: { nanos: 300000000, seconds: '19' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'code',
            endTime: { nanos: 0, seconds: '20' },
            startTime: { nanos: 500000000, seconds: '19' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'version',
            endTime: { nanos: 400000000, seconds: '20' },
            startTime: { nanos: 0, seconds: '20' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'of',
            endTime: { nanos: 600000000, seconds: '20' },
            startTime: { nanos: 400000000, seconds: '20' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'that',
            endTime: { nanos: 0, seconds: '21' },
            startTime: { nanos: 600000000, seconds: '20' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'still',
            endTime: { nanos: 900000000, seconds: '21' },
            startTime: { nanos: 0, seconds: '21' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'working',
            endTime: { nanos: 200000000, seconds: '22' },
            startTime: { nanos: 900000000, seconds: '21' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'progress.',
            endTime: { nanos: 500000000, seconds: '22' },
            startTime: { nanos: 200000000, seconds: '22' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'So',
            endTime: { nanos: 0, seconds: '23' },
            startTime: { nanos: 500000000, seconds: '22' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'if',
            endTime: { nanos: 500000000, seconds: '23' },
            startTime: { nanos: 0, seconds: '23' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'you',
            endTime: { nanos: 800000000, seconds: '23' },
            startTime: { nanos: 500000000, seconds: '23' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'are',
            endTime: { nanos: 900000000, seconds: '23' },
            startTime: { nanos: 800000000, seconds: '23' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'Developer',
            endTime: { nanos: 700000000, seconds: '24' },
            startTime: { nanos: 900000000, seconds: '23' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'and',
            endTime: { nanos: 200000000, seconds: '25' },
            startTime: { nanos: 700000000, seconds: '24' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'you',
            endTime: { nanos: 600000000, seconds: '25' },
            startTime: { nanos: 200000000, seconds: '25' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'can',
            endTime: { nanos: 800000000, seconds: '25' },
            startTime: { nanos: 600000000, seconds: '25' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'cross',
            endTime: { nanos: 0, seconds: '26' },
            startTime: { nanos: 800000000, seconds: '25' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 200000000, seconds: '26' },
            startTime: { nanos: 0, seconds: '26' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'code,',
            endTime: { nanos: 400000000, seconds: '26' },
            startTime: { nanos: 200000000, seconds: '26' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'you',
            endTime: { nanos: 600000000, seconds: '26' },
            startTime: { nanos: 400000000, seconds: '26' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'understand,',
            endTime: { nanos: 0, seconds: '27' },
            startTime: { nanos: 600000000, seconds: '26' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'it',
            endTime: { nanos: 100000000, seconds: '27' },
            startTime: { nanos: 0, seconds: '27' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'would',
            endTime: { nanos: 800000000, seconds: '27' },
            startTime: { nanos: 100000000, seconds: '27' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'very',
            endTime: { nanos: 0, seconds: '28' },
            startTime: { nanos: 800000000, seconds: '27' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'much',
            endTime: { nanos: 0, seconds: '28' },
            startTime: { nanos: 0, seconds: '28' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'like',
            endTime: { nanos: 500000000, seconds: '28' },
            startTime: { nanos: 0, seconds: '28' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'help',
            endTime: { nanos: 500000000, seconds: '29' },
            startTime: { nanos: 500000000, seconds: '28' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'in',
            endTime: { nanos: 100000000, seconds: '30' },
            startTime: { nanos: 500000000, seconds: '29' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'maintaining,',
            endTime: { nanos: 100000000, seconds: '31' },
            startTime: { nanos: 100000000, seconds: '30' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'so',
            endTime: { nanos: 700000000, seconds: '31' },
            startTime: { nanos: 100000000, seconds: '31' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'rather',
            endTime: { nanos: 100000000, seconds: '32' },
            startTime: { nanos: 700000000, seconds: '31' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'actually',
            endTime: { nanos: 600000000, seconds: '32' },
            startTime: { nanos: 100000000, seconds: '32' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'improving',
            endTime: { nanos: 0, seconds: '33' },
            startTime: { nanos: 600000000, seconds: '32' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 100000000, seconds: '33' },
            startTime: { nanos: 0, seconds: '33' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'code',
            endTime: { nanos: 400000000, seconds: '33' },
            startTime: { nanos: 100000000, seconds: '33' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'and',
            endTime: { nanos: 500000000, seconds: '33' },
            startTime: { nanos: 400000000, seconds: '33' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'then',
            endTime: { nanos: 500000000, seconds: '33' },
            startTime: { nanos: 500000000, seconds: '33' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'obviously',
            endTime: { nanos: 700000000, seconds: '33' },
            startTime: { nanos: 500000000, seconds: '33' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'maintaining',
            endTime: { nanos: 400000000, seconds: '34' },
            startTime: { nanos: 700000000, seconds: '33' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'it',
            endTime: { nanos: 600000000, seconds: '34' },
            startTime: { nanos: 400000000, seconds: '34' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'if',
            endTime: { nanos: 100000000, seconds: '35' },
            startTime: { nanos: 600000000, seconds: '34' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: "it's",
            endTime: { nanos: 300000000, seconds: '35' },
            startTime: { nanos: 100000000, seconds: '35' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'useful,',
            endTime: { nanos: 200000000, seconds: '36' },
            startTime: { nanos: 300000000, seconds: '35' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'and',
            endTime: { nanos: 100000000, seconds: '37' },
            startTime: { nanos: 200000000, seconds: '36' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'this',
            endTime: { nanos: 200000000, seconds: '37' },
            startTime: { nanos: 100000000, seconds: '37' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'is',
            endTime: { nanos: 300000000, seconds: '37' },
            startTime: { nanos: 200000000, seconds: '37' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'just',
            endTime: { nanos: 400000000, seconds: '37' },
            startTime: { nanos: 300000000, seconds: '37' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'a',
            endTime: { nanos: 600000000, seconds: '37' },
            startTime: { nanos: 400000000, seconds: '37' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'demo',
            endTime: { nanos: 900000000, seconds: '37' },
            startTime: { nanos: 600000000, seconds: '37' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'video',
            endTime: { nanos: 0, seconds: '38' },
            startTime: { nanos: 900000000, seconds: '37' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'of',
            endTime: { nanos: 400000000, seconds: '39' },
            startTime: { nanos: 0, seconds: '38' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 900000000, seconds: '39' },
            startTime: { nanos: 400000000, seconds: '39' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'audio',
            endTime: { nanos: 0, seconds: '41' },
            startTime: { nanos: 900000000, seconds: '39' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'is',
            endTime: { nanos: 200000000, seconds: '41' },
            startTime: { nanos: 0, seconds: '41' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'being',
            endTime: { nanos: 300000000, seconds: '41' },
            startTime: { nanos: 200000000, seconds: '41' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'transcribed',
            endTime: { nanos: 700000000, seconds: '41' },
            startTime: { nanos: 300000000, seconds: '41' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'right',
            endTime: { nanos: 800000000, seconds: '42' },
            startTime: { nanos: 700000000, seconds: '41' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'now',
            endTime: { nanos: 0, seconds: '43' },
            startTime: { nanos: 800000000, seconds: '42' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'with',
            endTime: { nanos: 600000000, seconds: '43' },
            startTime: { nanos: 0, seconds: '43' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'motion',
            endTime: { nanos: 200000000, seconds: '44' },
            startTime: { nanos: 600000000, seconds: '43' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'box,',
            endTime: { nanos: 500000000, seconds: '44' },
            startTime: { nanos: 200000000, seconds: '44' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'but',
            endTime: { nanos: 900000000, seconds: '44' },
            startTime: { nanos: 500000000, seconds: '44' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: "I'm",
            endTime: { nanos: 900000000, seconds: '44' },
            startTime: { nanos: 900000000, seconds: '44' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'going',
            endTime: { nanos: 100000000, seconds: '45' },
            startTime: { nanos: 900000000, seconds: '44' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'to',
            endTime: { nanos: 200000000, seconds: '45' },
            startTime: { nanos: 100000000, seconds: '45' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'copy',
            endTime: { nanos: 500000000, seconds: '45' },
            startTime: { nanos: 200000000, seconds: '45' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 300000000, seconds: '46' },
            startTime: { nanos: 500000000, seconds: '45' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'JSON',
            endTime: { nanos: 700000000, seconds: '46' },
            startTime: { nanos: 300000000, seconds: '46' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'and',
            endTime: { nanos: 900000000, seconds: '46' },
            startTime: { nanos: 700000000, seconds: '46' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'just',
            endTime: { nanos: 100000000, seconds: '47' },
            startTime: { nanos: 900000000, seconds: '46' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'paste',
            endTime: { nanos: 400000000, seconds: '47' },
            startTime: { nanos: 100000000, seconds: '47' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'it',
            endTime: { nanos: 600000000, seconds: '47' },
            startTime: { nanos: 400000000, seconds: '47' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'in',
            endTime: { nanos: 800000000, seconds: '47' },
            startTime: { nanos: 600000000, seconds: '47' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 900000000, seconds: '47' },
            startTime: { nanos: 800000000, seconds: '47' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'root',
            endTime: { nanos: 200000000, seconds: '48' },
            startTime: { nanos: 900000000, seconds: '47' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'directory',
            endTime: { nanos: 300000000, seconds: '48' },
            startTime: { nanos: 200000000, seconds: '48' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'or',
            endTime: { nanos: 800000000, seconds: '48' },
            startTime: { nanos: 300000000, seconds: '48' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'in',
            endTime: { nanos: 100000000, seconds: '49' },
            startTime: { nanos: 800000000, seconds: '48' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 300000000, seconds: '49' },
            startTime: { nanos: 100000000, seconds: '49' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'end',
            endTime: { nanos: 700000000, seconds: '50' },
            startTime: { nanos: 300000000, seconds: '49' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'I',
            endTime: { nanos: 800000000, seconds: '50' },
            startTime: { nanos: 700000000, seconds: '50' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'guess,',
            endTime: { nanos: 100000000, seconds: '51' },
            startTime: { nanos: 800000000, seconds: '50' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'whatever',
            endTime: { nanos: 500000000, seconds: '51' },
            startTime: { nanos: 100000000, seconds: '51' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'directory',
            endTime: { nanos: 200000000, seconds: '52' },
            startTime: { nanos: 500000000, seconds: '51' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'in',
            endTime: { nanos: 700000000, seconds: '52' },
            startTime: { nanos: 200000000, seconds: '52' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'their',
            endTime: { nanos: 900000000, seconds: '52' },
            startTime: { nanos: 700000000, seconds: '52' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'repeal',
            endTime: { nanos: 300000000, seconds: '53' },
            startTime: { nanos: 900000000, seconds: '52' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'so',
            endTime: { nanos: 500000000, seconds: '54' },
            startTime: { nanos: 300000000, seconds: '53' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'that',
            endTime: { nanos: 700000000, seconds: '54' },
            startTime: { nanos: 500000000, seconds: '54' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'you',
            endTime: { nanos: 800000000, seconds: '54' },
            startTime: { nanos: 700000000, seconds: '54' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'can',
            endTime: { nanos: 900000000, seconds: '54' },
            startTime: { nanos: 800000000, seconds: '54' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'see',
            endTime: { nanos: 0, seconds: '55' },
            startTime: { nanos: 900000000, seconds: '54' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 100000000, seconds: '55' },
            startTime: { nanos: 0, seconds: '55' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'shape',
            endTime: { nanos: 400000000, seconds: '55' },
            startTime: { nanos: 100000000, seconds: '55' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'of',
            endTime: { nanos: 500000000, seconds: '55' },
            startTime: { nanos: 400000000, seconds: '55' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 800000000, seconds: '55' },
            startTime: { nanos: 500000000, seconds: '55' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'transcription.',
            endTime: { nanos: 400000000, seconds: '56' },
            startTime: { nanos: 800000000, seconds: '55' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'And',
            endTime: { nanos: 0, seconds: '58' },
            startTime: { nanos: 400000000, seconds: '56' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'so',
            endTime: { nanos: 200000000, seconds: '58' },
            startTime: { nanos: 0, seconds: '58' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'a',
            endTime: { nanos: 200000000, seconds: '58' },
            startTime: { nanos: 200000000, seconds: '58' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'lot',
            endTime: { nanos: 300000000, seconds: '58' },
            startTime: { nanos: 200000000, seconds: '58' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'of',
            endTime: { nanos: 400000000, seconds: '58' },
            startTime: { nanos: 300000000, seconds: '58' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: "stuff's",
            endTime: { nanos: 700000000, seconds: '58' },
            startTime: { nanos: 400000000, seconds: '58' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'going',
            endTime: { nanos: 800000000, seconds: '58' },
            startTime: { nanos: 700000000, seconds: '58' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'to',
            endTime: { nanos: 0, seconds: '59' },
            startTime: { nanos: 800000000, seconds: '58' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'be',
            endTime: { nanos: 0, seconds: '59' },
            startTime: { nanos: 0, seconds: '59' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'hard',
            endTime: { nanos: 200000000, seconds: '59' },
            startTime: { nanos: 0, seconds: '59' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'coded',
            endTime: { nanos: 500000000, seconds: '59' },
            startTime: { nanos: 200000000, seconds: '59' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'but',
            endTime: { nanos: 700000000, seconds: '59' },
            startTime: { nanos: 500000000, seconds: '59' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'yeah.',
            endTime: { nanos: 0, seconds: '60' },
            startTime: { nanos: 700000000, seconds: '59' },
            confidence: 0,
            speakerTag: 0,
          },
        ],
        confidence: 0.9670090079307556,
        transcript:
          "Hey there. Thanks for checking out this open source tool. What did stool is, is kind of like a d script editor, where the text is the primary source of the cuts in the edits for the video. So the idea is to give an edited video like a Word document in this is an open source code version of that still working progress. So if you are Developer and you can cross the code, you understand, it would very much like help in maintaining, so rather actually improving the code and then obviously maintaining it if it's useful, and this is just a demo video of the audio is being transcribed right now with motion box, but I'm going to copy the Jason and just paste it in the root directory or in the end I guess, whatever directory in their repeal so that you can see the shape of the transcription. And so a lot of stuff's going to be hard coated but yeah.",
      },
    ],
    languageCode: 'en-us',
    resultEndTime: { nanos: 260000000, seconds: '60' },
  },
  {
    channelTag: 0,
    alternatives: [
      {
        words: [
          {
            word: 'if',
            endTime: { nanos: 600000000, seconds: '60' },
            startTime: { nanos: 300000000, seconds: '60' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: "you'd",
            endTime: { nanos: 800000000, seconds: '60' },
            startTime: { nanos: 600000000, seconds: '60' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'like',
            endTime: { nanos: 0, seconds: '61' },
            startTime: { nanos: 800000000, seconds: '60' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'to',
            endTime: { nanos: 200000000, seconds: '61' },
            startTime: { nanos: 0, seconds: '61' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'use',
            endTime: { nanos: 200000000, seconds: '61' },
            startTime: { nanos: 200000000, seconds: '61' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'this',
            endTime: { nanos: 500000000, seconds: '61' },
            startTime: { nanos: 200000000, seconds: '61' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'in',
            endTime: { nanos: 900000000, seconds: '61' },
            startTime: { nanos: 500000000, seconds: '61' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'your',
            endTime: { nanos: 200000000, seconds: '62' },
            startTime: { nanos: 900000000, seconds: '61' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'own',
            endTime: { nanos: 300000000, seconds: '63' },
            startTime: { nanos: 200000000, seconds: '62' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'software,',
            endTime: { nanos: 600000000, seconds: '63' },
            startTime: { nanos: 300000000, seconds: '63' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'you',
            endTime: { nanos: 300000000, seconds: '64' },
            startTime: { nanos: 600000000, seconds: '63' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'can',
            endTime: { nanos: 300000000, seconds: '64' },
            startTime: { nanos: 300000000, seconds: '64' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'just',
            endTime: { nanos: 600000000, seconds: '64' },
            startTime: { nanos: 300000000, seconds: '64' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'copy',
            endTime: { nanos: 400000000, seconds: '65' },
            startTime: { nanos: 600000000, seconds: '64' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'some',
            endTime: { nanos: 700000000, seconds: '65' },
            startTime: { nanos: 400000000, seconds: '65' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'of',
            endTime: { nanos: 700000000, seconds: '65' },
            startTime: { nanos: 700000000, seconds: '65' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 800000000, seconds: '65' },
            startTime: { nanos: 700000000, seconds: '65' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'components',
            endTime: { nanos: 100000000, seconds: '66' },
            startTime: { nanos: 800000000, seconds: '65' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'and',
            endTime: { nanos: 800000000, seconds: '66' },
            startTime: { nanos: 100000000, seconds: '66' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'improvements',
            endTime: { nanos: 900000000, seconds: '70' },
            startTime: { nanos: 800000000, seconds: '66' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'to',
            endTime: { nanos: 400000000, seconds: '72' },
            startTime: { nanos: 900000000, seconds: '70' },
            confidence: 0,
            speakerTag: 0,
          },
        ],
        confidence: 0.9146847724914551,
        transcript:
          " if you'd like to use this in your own software, you can just copy some of the components and improvements to",
      },
    ],
    languageCode: 'en-us',
    resultEndTime: { nanos: 820000000, seconds: '74' },
  },
  {
    channelTag: 0,
    alternatives: [
      {
        words: [
          {
            word: 'Add',
            endTime: { nanos: 0, seconds: '76' },
            startTime: { nanos: 400000000, seconds: '75' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'on',
            endTime: { nanos: 300000000, seconds: '76' },
            startTime: { nanos: 0, seconds: '76' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'into',
            endTime: { nanos: 700000000, seconds: '76' },
            startTime: { nanos: 300000000, seconds: '76' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'the',
            endTime: { nanos: 700000000, seconds: '76' },
            startTime: { nanos: 700000000, seconds: '76' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'project',
            endTime: { nanos: 0, seconds: '77' },
            startTime: { nanos: 700000000, seconds: '76' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'and',
            endTime: { nanos: 300000000, seconds: '77' },
            startTime: { nanos: 0, seconds: '77' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'so',
            endTime: { nanos: 500000000, seconds: '77' },
            startTime: { nanos: 300000000, seconds: '77' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'do',
            endTime: { nanos: 200000000, seconds: '78' },
            startTime: { nanos: 500000000, seconds: '77' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'you',
            endTime: { nanos: 200000000, seconds: '78' },
            startTime: { nanos: 200000000, seconds: '78' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'have',
            endTime: { nanos: 300000000, seconds: '78' },
            startTime: { nanos: 200000000, seconds: '78' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'any',
            endTime: { nanos: 500000000, seconds: '78' },
            startTime: { nanos: 300000000, seconds: '78' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'suggestions',
            endTime: { nanos: 600000000, seconds: '79' },
            startTime: { nanos: 500000000, seconds: '78' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'and',
            endTime: { nanos: 600000000, seconds: '79' },
            startTime: { nanos: 600000000, seconds: '79' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'any',
            endTime: { nanos: 0, seconds: '80' },
            startTime: { nanos: 600000000, seconds: '79' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'ideas',
            endTime: { nanos: 800000000, seconds: '80' },
            startTime: { nanos: 0, seconds: '80' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'on',
            endTime: { nanos: 900000000, seconds: '80' },
            startTime: { nanos: 800000000, seconds: '80' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'how',
            endTime: { nanos: 100000000, seconds: '81' },
            startTime: { nanos: 900000000, seconds: '80' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'to',
            endTime: { nanos: 100000000, seconds: '81' },
            startTime: { nanos: 100000000, seconds: '81' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'improve,',
            endTime: { nanos: 200000000, seconds: '81' },
            startTime: { nanos: 100000000, seconds: '81' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'Please',
            endTime: { nanos: 300000000, seconds: '82' },
            startTime: { nanos: 200000000, seconds: '81' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'send',
            endTime: { nanos: 700000000, seconds: '82' },
            startTime: { nanos: 300000000, seconds: '82' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'a',
            endTime: { nanos: 800000000, seconds: '82' },
            startTime: { nanos: 700000000, seconds: '82' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'pull',
            endTime: { nanos: 0, seconds: '83' },
            startTime: { nanos: 800000000, seconds: '82' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'request',
            endTime: { nanos: 200000000, seconds: '83' },
            startTime: { nanos: 0, seconds: '83' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'to',
            endTime: { nanos: 300000000, seconds: '83' },
            startTime: { nanos: 200000000, seconds: '83' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'be',
            endTime: { nanos: 500000000, seconds: '83' },
            startTime: { nanos: 300000000, seconds: '83' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'really',
            endTime: { nanos: 800000000, seconds: '83' },
            startTime: { nanos: 500000000, seconds: '83' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'helpful,',
            endTime: { nanos: 800000000, seconds: '83' },
            startTime: { nanos: 800000000, seconds: '83' },
            confidence: 0,
            speakerTag: 0,
          },
          {
            word: 'thanks.',
            endTime: { nanos: 400000000, seconds: '84' },
            startTime: { nanos: 800000000, seconds: '83' },
            confidence: 0,
            speakerTag: 0,
          },
        ],
        confidence: 0.8939058184623718,
        transcript:
          ' Add on into the project and so do you have any suggestions and any ideas on how to improve, Please send up for us to be really helpful, thanks.',
      },
    ],
    languageCode: 'en-us',
    resultEndTime: { nanos: 970000000, seconds: '84' },
  },
];

export default transcription;
